# Generated by Django 3.0.14 on 2021-05-13 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('age', models.IntegerField()),
                ('photo', models.ImageField(upload_to='photos')),
                ('parents_phonenumber', models.CharField(max_length=50, null=True)),
                ('parents_Email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.CharField(max_length=200)),
                ('stage_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='school_management_app.Stage')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=550)),
                ('age', models.IntegerField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos')),
                ('salary', models.CharField(max_length=50)),
                ('phonenumber', models.CharField(max_length=50, null=True)),
                ('Email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.CharField(max_length=50)),
                ('Departments', models.CharField(max_length=50)),
                ('Degree', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher_Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('موجود', 'موجود'), ('غائب', 'غائب'), ('في اجازة', 'في اجازة')], max_length=50)),
                ('date', models.DateField()),
                ('name_Teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='school_management_app.Teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Student_Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('موجود', 'موجود'), ('غائب', 'غائب'), ('في اجازة', 'في اجازة')], max_length=50)),
                ('date', models.DateField()),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='school_management_app.Stage')),
                ('name_Student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='school_management_app.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Marks_semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject_name1', models.CharField(blank=True, max_length=50, null=True)),
                ('Subject_mark1', models.CharField(blank=True, max_length=50, null=True)),
                ('Subject_name2', models.CharField(blank=True, max_length=50, null=True)),
                ('Subject_mark2', models.CharField(blank=True, max_length=50, null=True)),
                ('Subject_name3', models.CharField(blank=True, max_length=50, null=True)),
                ('Subject_mark3', models.CharField(blank=True, max_length=50, null=True)),
                ('Subject_name4', models.CharField(blank=True, max_length=50, null=True)),
                ('Subject_mark4', models.CharField(blank=True, max_length=50, null=True)),
                ('Subject_name5', models.CharField(blank=True, max_length=50, null=True)),
                ('Subject_mark5', models.CharField(blank=True, max_length=50, null=True)),
                ('Subject_name6', models.CharField(blank=True, max_length=50, null=True)),
                ('Subject_mark6', models.CharField(blank=True, max_length=50, null=True)),
                ('Subject_name7', models.CharField(blank=True, max_length=50, null=True)),
                ('Subject_mark7', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('ناجح', 'ناجح'), ('مكمل', 'مكمل'), ('راسب', 'راسب')], max_length=50)),
                ('Subject_name8', models.CharField(blank=True, max_length=50, null=True)),
                ('Subject_mark8', models.CharField(blank=True, max_length=50, null=True)),
                ('Subject_name9', models.CharField(blank=True, max_length=50, null=True)),
                ('Subject_mark9', models.CharField(blank=True, max_length=50, null=True)),
                ('Subject_name10', models.CharField(blank=True, max_length=50, null=True)),
                ('Subject_mark10', models.CharField(blank=True, max_length=50, null=True)),
                ('Subject_name11', models.CharField(blank=True, max_length=50, null=True)),
                ('Subject_mark11', models.CharField(blank=True, max_length=50, null=True)),
                ('Subject_name12', models.CharField(blank=True, max_length=50, null=True)),
                ('Subject_mark12', models.CharField(blank=True, max_length=50, null=True)),
                ('Subject_name13', models.CharField(blank=True, max_length=50, null=True)),
                ('Subject_mark13', models.CharField(blank=True, max_length=50, null=True)),
                ('Subject_name14', models.CharField(blank=True, max_length=50, null=True)),
                ('Subject_mark14', models.CharField(blank=True, max_length=50, null=True)),
                ('status2', models.CharField(choices=[('ناجح', 'ناجح'), ('مكمل', 'مكمل'), ('راسب', 'راسب')], max_length=50)),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='school_management_app.Stage')),
                ('student_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='school_management_app.Student')),
            ],
        ),
    ]
